target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'composeApp', :path => '../composeApp'

  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-6'    # Swift Concurrency implementation
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-6'  # Combine implementation
  pod 'KMPNativeCoroutinesRxSwift', '1.0.0-ALPHA-6'  # RxSwift implementation
  pod 'KMMViewModelSwiftUI', '1.0.0-ALPHA-6'
  pod 'SwiftLint', '0.43.1'
  pod 'Kingfisher', '~> 7.0'
end
